### ISSUE TITLE
Using multiple cookies in parallel

### ISSUE THREAD

**Issue by deepdatalive** [EvanZhouDev/bard-ai#11]
Can I create and use multiple objects using 2 or more cookies in the same JS code?

**Comment by EvanZhouDev** [comment]
You cannot do this right now, though I am completely open to implementing this. However, may I ask you why you would want to do this? You are able to create multiple conversations already.

**Comment by deepdatalive** [comment]
Want to avoid the risk of getting rate limited during multiple conversations, fetching a new object for each cookie might be good.

**Comment by EvanZhouDev** [comment]
Hmm... very interesting idea.

Would you be fine with initialization becoming something like this?
```js
await Bard.init(COOKIE1, COOKIE2, ...more cookies...)
```

When being called on the inside, it will sequentially go through the cookies to ensure minimal rate-limiting.

**Comment by ThatXliner** [comment]
> Hmm... very interesting idea.
> 
> Would you be fine with initialization becoming something like this?
> 
> ```js
> await Bard.init(COOKIE1, COOKIE2, ...more cookies...)
> ```
> 
> When being called on the inside, it will sequentially go through the cookies to ensure minimal rate-limiting.

I think better API design would be having an additional cookie parameter when initializing Chat or askAI; that way this could be implemented user-side (along with any other cookie shenanigans)

**Comment by EvanZhouDev** [comment]
The thing is, cookies have to go through an initialization process, to become a usable ID. Without that ID, I can't process requests. Therefore, its pretty hard to make it local to Chat or askAI, as that would require an extra long initialization time...

**Comment by EvanZhouDev** [comment]
Yes, I think that #12 would work to your purpose... see my comment underneath; I think it may work something like this...
> Okay wait, I think I got it wrong; Is this something like what you are thinking?
> 
> ```js
> let SNlM0e_1 = Bard.init(COOKIE_KEY_1)
> let SNlM0e_2 = Bard.init(COOKIE_KEY_2)
> 
> askAI("hi", COOKIE_KEY_1)
> askAI("hi2", COOKIE_KEY_2)
> ```
> 
> If it is, then its all good to go, I'll just do some minor changes...

That way, you can write your own cookie cycling code.

**Comment by deepdatalive** [comment]
> Hmm... very interesting idea.
> 
> Would you be fine with initialization becoming something like this?
> 
> ```js
> await Bard.init(COOKIE1, COOKIE2, ...more cookies...)
> ```
> 
> When being called on the inside, it will sequentially go through the cookies to ensure minimal rate-limiting.

This would solve one use-case 

However, different objects would be great as well to fit other use-cases

**Comment by EvanZhouDev** [comment]
Yes, we are in the process of revamping all of this. Please stay tuned!

**Comment by EvanZhouDev** [comment]
Does #15 look good to you?

**Comment by EvanZhouDev** [comment]
Multi-cookie use will be available in Version 2. See #30.

Closing... feel free to re-open if necessary.
