### ISSUE TITLE
Custom Request Callback to Google API

### ISSUE THREAD

**Issue by Aldhanekaa** [EvanZhouDev/bard-ai#14]
When I develop my application using this library in `Electron` Application environment (Obsidian Application), it denies request (because it is a request from client, not a server) as this issue experience https://github.com/EvanZhouDev/bard-ai/issues/2 . 

Well I've managed to solve it, by requesting to Google Bard API using [Obsidian Plugin requestUrl](https://docs.obsidian.md/Reference/TypeScript+API/requestUrl) and therefore I rewrite all of this library codebase to my project (really inefficient) . 

I think, it is important to add custom request callback, if a user faced the same issue as me, and they can be Electron Developers, or JavaScript Mobile Application Developers.

---

What do you guys think?

**Comment by EvanZhouDev** [comment]
Okay, so this a very good idea, and I would like this, but the thing is, it has to have the exact same syntax as native `fetch`. I that statement holds true, then its super easy to implement.

**Comment by EvanZhouDev** [comment]
Also, how do you propose we go about setting the `fetch` alternative?

**Comment by Aldhanekaa** [comment]
> Also, how do you propose we go about setting the `fetch` alternative?

> Okay, so this a very good idea, and I would like this, but the thing is, your callback has to have the exact same syntax as native `fetch`. If that statement holds true, then it's super easy to implement.

I think there are two possible solutinos;
- Add callback to `queryBard` function. Well for sure, `askAI` and `class Chat` constructor should have the same. 
- Or add callback to `init` function, and let it define the callback to global variable 

Regarding of this, I'm quiet concern about performance, because, people may only need to define only once custom request callback.

**Comment by EvanZhouDev** [comment]
What do you mean performance?

**Comment by Aldhanekaa** [comment]
> What do you mean performance?

Well, since I'm not an expert in JS, I don't really know which may be great in terms of passing callback. 

But in terms of efficiency, people may only need to define one custom request callback, I think it is ineffective if they had to pass callback to `class Chat` constructor or `askAI` function.

**Comment by EvanZhouDev** [comment]
Yeah that's pretty obvious, as its pretty rare to have to switch fetch function...

**Comment by Aldhanekaa** [comment]
> Yeah that's pretty obvious, as its pretty rare to have to switch fetch function...

Yeah I also agree, pretty rare

**Comment by ThatXliner** [comment]
You could always just [patch global fetch](https://bard-ai-docs.vercel.app/fetch).

~~On the other hand, I would imagine other use cases of swapping out the fetch function being SSR (maybe?), replacing it with some sort of isomorphic fetch, or unit testing (which is our problem in the first place).~~

**Comment by Aldhanekaa** [comment]
> You could always just [patch global fetch](https://bard-ai-docs.vercel.app/fetch).
> 
> ~On the other hand, I would imagine other use cases of swapping out the fetch function being SSR (maybe?), replacing it with some sort of isomorphic fetch, or unit testing (which is our problem in the first place).~

Oh interesting, I'll try to use it. I'll close this once I've done experimenting with it!

**Comment by EvanZhouDev** [comment]
Custom callbacks will be available in Version 2. See #30.

Closing... feel free to re-open if necessary.
