### ISSUE TITLE
Error when using the bard-ai in Discord.js (Typescript)

### ISSUE THREAD

**Issue by mashwishi** [EvanZhouDev/bard-ai#19]
I attempted to migrate to this library, to evaluate its performance compared to the 'googlebard' library. However, I encountered an error while trying to use it. I also need clarification on whether this module has bypassed the recent update of Google Bard AI. Please note that the code provided is written in TypeScript.

**Code:**
```ts
if (messageContent && typeof messageContent === "string" && !message.author.bot) {
    // New Code using EvanZhouDev/bard-ai/
    let COOKIE_KEY = process.env.BARD_COOKIES || "";
    await Bard.init(COOKIE_KEY);
    let response = await askAI(messageContent);
    await message.reply(response.substring(0, 2000));

    // My previous code with googlebard
    // let importDynamic = new Function('modulePath', 'return import(modulePath)')
    // const { Bard } = await importDynamic("googlebard")
    // let bot =new Bard(cookies, {
    //     inMemory: false, 
    //     savePath: "./conversations.json", 
    //     proxy: {
    //         host: process.env.PROXY_HOST,
    //         port: process.env.PROXY_PORT,
    //         auth: {
    //             username: process.env.PROXY_USERNAME,
    //             password: process.env.PROXY_PASSWORD,
    //         },
    //         protocol: "https",
    //     },
    // });
    // let response = await bot.ask(messageContent, user_id);
} else {
    await message.reply("I can only process text messages.");
}
```

**Error Message:** `'askAI' only refers to a type, but is being used as a value here.ts(2693)`

**Steps to Reproduce:**
1. Ensure the required environment variables are properly set.
2. Execute the provided code in a TypeScript project.
3. Observe the error message 'askAI' only refers to a type, but is being used as a value here.ts(2693).

**Expected Behavior:**
- The code should successfully utilize the 'EvanZhouDev/bard-ai' library to interact with the AI model and provide a response to the user message.

**Additional Information:**
- This code snippet attempts to migrate from the googlebard library to bard-ai for enhanced performance evaluation.
- The error message suggests that the identifier 'askAI' is being treated as a type rather than a value, causing the compilation error.
- Please provide guidance on resolving this error and clarify if bard-ai has bypassed the recent update of Google Bard AI.

Please let me know if you need any further information. Thank you!

**Comment by ThatXliner** [comment]
This seems to just be a type error on our part. Does the library still function correctly when run?

@EvanZhouDev did we publish the updated types?

**Comment by mashwishi** [comment]
Let me know

**Comment by EvanZhouDev** [comment]
> This seems to just be a type error on our part. Does the library still function correctly when run?
> 
> @EvanZhouDev did we publish the updated types?

Uh... We should have? @mashwishi Feel free to join the slack, and let's talk about it... https://join.slack.com/t/bard-aiworkspace/shared_invite/zt-1y1g3570m-Hx_N3IShMYBMkR6jpRyRjw

**Comment by EvanZhouDev** [comment]
Also, tell me more about "bypassed recent update"... Do you mean the one a few days ago? https://github.com/EvanZhouDev/bard-ai/issues/16
If so, then yes...

**Comment by EvanZhouDev** [comment]
@mashwishi Try updating to `v1.5.0`. We have pushed some updated types.

**Comment by mashwishi** [comment]
@EvanZhouDev okay, I'll let you know...

**Comment by mashwishi** [comment]
I also tried this:
```ts
            let COOKIE_KEY = process.env.BARD_COOKIES || "";
            let importDynamic = new Function('modulePath', 'return import(modulePath)')
            const Bard = await importDynamic("bard-ai")
            await Bard.init(COOKIE_KEY)
            let question = new Bard.Chat();
            let response = await question.ask(messageContent);
            await message.reply(response);
            console.log(response)
```

My reference is docs: https://bard-ai-docs.vercel.app/basics/chat
```js
import Bard from "bard-ai";
 
await Bard.init(COOKIE_KEY);
 
let myConversation = new Bard.Chat();
console.log(await myConversation.ask("How are you?"));
console.log(await myConversation.ask("What's the last thing I said?"));
```


Error:
```log
node:events:505
      throw er; // Unhandled 'error' event
      ^

ReferenceError: fetch is not defined
    at Module.init (file:///D:/Mechi-Discord-TS/node_modules/bard-ai/index.js:18:22)
    at D:\Mechi-Discord-TS\build\events\messageCreate.js:63:40
    at Generator.next (<anonymous>)
    at fulfilled (D:\Mechi-Discord-TS\build\events\messageCreate.js:5:58)
Emitted 'error' event on Client instance at:
    at emitUnhandledRejectionOrErr (node:events:384:10)
    at processTicksAndRejections (node:internal/process/task_queues:85:21)
    ```

**Comment by mashwishi** [comment]
Looks like i am close to make this work, please let me know if you have any idea about this.
```ts
      let importDynamic = new Function('modulePath', 'return import(modulePath)');
      const Bard = await importDynamic("bard-ai");
      await Bard.init(cookies);
      let response = new Bard.ask(messageContent);
      await message.reply(response);
```

Error:
```log
node:events:505
      throw er; // Unhandled 'error' event
      ^

ReferenceError: fetch is not defined
    at Module.init (file:///D:/Mechi-Discord-TS/node_modules/bard-ai/index.js:18:22)
    at D:\Mechi-Discord-TS\build\events\messageCreate.js:72:40
    at Generator.next (<anonymous>)
    at fulfilled (D:\Mechi-Discord-TS\build\events\messageCreate.js:5:58)
Emitted 'error' event on Client instance at:
    at emitUnhandledRejectionOrErr (node:events:384:10)
    at processTicksAndRejections (node:internal/process/task_queues:85:21)
```

**Comment by ThatXliner** [comment]
Your API usage seems to be wrong. The only public members that are in the API is `init`, `Chat` (a class), and `askAI`. 

```javascript
      let importDynamic = new Function('modulePath', 'return import(modulePath)');
      const Bard = await importDynamic("bard-ai");
      await Bard.init(cookies);
      let response = await Bard.askAI(messageContent);
      await message.reply(response);
```

additionally, the error message mentions `ReferenceError: fetch is not defined`. You may need to install a [polyfill](https://bard-ai-docs.vercel.app/fetch)

**Comment by mashwishi** [comment]
I tried it now using a server end instead of discord bot also code is now written in JS:

```js
import express from 'express';
import axios from 'axios';
import * as dotenv from 'dotenv';
import cors from 'cors';
import { Configuration, OpenAIApi } from 'openai';
import Bard, { askAI } from "bard-ai";

dotenv.config();

const app = express();
app.use(cors());
app.use(express.json());

app.get('/', async (req, res) => {
  res.status(200).send({
    message: 'Server - Last Update July 3, 2023',
  })
});

app.post('/', async (req, res) => {
  const is_bard = req.body.is_bard;

  if(is_bard) {
    
    const user_message = req.body.user_message;

    try {
      await Bard.init(process.env.BARD_COOKIES);

      const response = await askAI(user_message)
      console.log(response)

      res.status(200).send({
        bot: response
      });

    } catch (error) {
      console.error(error)
    }
  }else{
    //OPEN AI CODE HERE
  }

})

app.listen(5500, () => console.log('Server Started on port 5500'))
```

Request Body:
```json
{
  "user_message": "How are you today?",
  "is_bard": true
}
```

Error:
```log
Server Started on port 5500
ReferenceError: fetch is not defined
    at Object.init (file:///D:/Mash-Server/node_modules/bard-ai/index.js:18:22)
    at file:///D:/Mash-Server/server.js:28:18
    at Layer.handle [as handle_request] (D:\Mash-Server\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\Mash-Server\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (D:\Mash-Server\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (D:\Mash-Server\node_modules\express\lib\router\layer.js:95:5)
    at D:\Mash-Server\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (D:\Mash-Server\node_modules\express\lib\router\index.js:346:12)
    at next (D:\Mash-Server\node_modules\express\lib\router\index.js:280:10)
    at D:\Mash-Server\node_modules\body-parser\lib\read.js:137:5
```

**Comment by mashwishi** [comment]
Oh i forgot to check this https://bard-ai-docs.vercel.app/fetch okay ill try it

**Comment by mashwishi** [comment]
**For the Discord Bot**

Code:
```ts
      let importDynamic = new Function('modulePath', 'return import(modulePath)');
      const Bard = await importDynamic("bard-ai");
      await Bard.init(cookies);
      let response = await Bard.ask(messageContent);
      await message.reply(response);
```
Error:
```log
node:events:505
      throw er; // Unhandled 'error' event
      ^
ReferenceError: fetch is not defined
```


Updated Code:
```ts
      let importDynamic = new Function('modulePath', 'return import(modulePath)');
      const Bard = await importDynamic("bard-ai");
      const fetch = await importDynamic("node-fetch");
      globalThis.fetch = fetch;
      await Bard.init(cookies);
      let response = await Bard.ask(messageContent);
      await message.reply(response);
```
Error:
```log
node:events:505
      throw er; // Unhandled 'error' event
      ^
TypeError: fetch is not a function
```

**Comment by EvanZhouDev** [comment]
Well, you're gonna need to polyfill fetch before the imports, I think.

**Comment by RFS-ADRENO** [comment]
> **For the Discord Bot**
> 
> Code:
> 
> ```ts
>       let importDynamic = new Function('modulePath', 'return import(modulePath)');
>       const Bard = await importDynamic("bard-ai");
>       await Bard.init(cookies);
>       let response = await Bard.ask(messageContent);
>       await message.reply(response);
> ```
> 
> Error:
> 
> ```
> node:events:505
>       throw er; // Unhandled 'error' event
>       ^
> ReferenceError: fetch is not defined
> ```
> 
> Updated Code:
> 
> ```ts
>       let importDynamic = new Function('modulePath', 'return import(modulePath)');
>       const Bard = await importDynamic("bard-ai");
>       const fetch = await importDynamic("node-fetch");
>       globalThis.fetch = fetch;
>       await Bard.init(cookies);
>       let response = await Bard.ask(messageContent);
>       await message.reply(response);
> ```
> 
> Error:
> 
> ```
> node:events:505
>       throw er; // Unhandled 'error' event
>       ^
> TypeError: fetch is not a function
> ```

why don't just use normal import but dynamic import?
Also what is this

> let importDynamic = new Function('modulePath', 'return import(modulePath)');

I don't think this is how dynamic import work...

**Comment by EvanZhouDev** [comment]
I think its because he's in a Common JS environment; `bard-ai` is a pure ESM library, as per most modern JS libraries. But indeed I think the dynamic import is handled correctly; though the error's on the fetch side? I am not too sure.

**Comment by RFS-ADRENO** [comment]
> I think its because he's in a Common JS environment; `bard-ai` is a pure ESM library, as per most modern JS libraries. But indeed I think the dynamic import is handled correctly; though the error's on the fetch side? I am not too sure.

Its not wrong, It's just no need. As far as I know, for dynamic import, just use normal import, like
> const fetch = await import("fetch")

and for the error, put the default after:

> const fetch = await importDynamic("node-fetch");
> globalThis.fetch = fetch.default;

**Comment by mashwishi** [comment]
> 

Error: Could not get Google Bard.
    at Module.init (file:///D:/Mechi-Server-2.0/node_modules/bard-ai/index.js:29:16)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async file:///D:/Mechi-Server-2.0/server.js:114:9

**Comment by mashwishi** [comment]
This is my server.js:
```js
import express from 'express';
import * as dotenv from 'dotenv';
import cors from 'cors';
import { Configuration, OpenAIApi } from 'openai';

dotenv.config();

const app = express();
app.use(cors());
app.use(express.json());

app.get('/', async (req, res) => {
  res.status(200).send({
    message: 'Server is Running!',
  })
});

app.post('/', async (req, res) => {

  const prompt = req.body.prompt;
  const message = req.body.message;
  const ai = req.body.ai;

  switch(ai) {
    case 'gpt':
      try {
        const OPENAI_API = process.env.OPENAI_API;
        const API_KEY = req.body.custom_api || OPENAI_API;
        const configuration = new Configuration({
      apiKey: API_KEY,
        });
        const openai = new OpenAIApi(configuration);
        const response = await openai.createChatCompletion({
          model: "gpt-3.5-turbo",
          messages: [
            {role: "system", content: `You are a very helpful assistant.`},
            ...prompt
          ],
          temperature: 0.2,
          max_tokens: 200,
          top_p: 1,
          frequency_penalty: 0,
          presence_penalty: 0,
        });
        res.status(200).send({ bot: response.data.choices[0].message.content });
        console.error(response.data.choices[0].message.content)
      } 
      catch (error) {
        res.status(500).send(error || 'Something went wrong! I am experiencing high volume of request at the moment, Please try again later.');
        console.error(error)
      }
      break;
    case 'bard':
      try {
        let importDynamic = new Function('modulePath', 'return import(modulePath)');
        const fetch = await importDynamic("node-fetch");
        globalThis.fetch = fetch.default;
        const Bard = await importDynamic("bard-ai");
        await Bard.init(process.env.BARD_COOKIES);
        let response = await Bard.ask(message);
        res.status(200).send({ bot: response });
        console.log(response)
      } 
      catch (error) {
        res.status(500).send(error || 'Something went wrong! I am experiencing high volume of request at the moment, Please try again later.');
        console.error(error)
      }
      break;
    default:
      res.status(500).send('No Artificial Intelligence found.');
  }

})

app.listen(5500, () => console.log('Server Started on port 5500'))
```

**Comment by EvanZhouDev** [comment]
> Error: Could not get Google Bard.
> at Module.init (file:///D:/Mechi-Server-2.0/node_modules/bard-ai/index.js:29:16)
> at processTicksAndRejections (node:internal/process/task_queues:96:5)
> at async file:///D:/Mechi-Server-2.0/server.js:114:9

Do you have access on the Bard website? Could you also make sure your PSID is correct?

**Comment by mashwishi** [comment]
> > Error: Could not get Google Bard.
> > at Module.init (file:///D:/Mechi-Server-2.0/node_modules/bard-ai/index.js:29:16)
> > at processTicksAndRejections (node:internal/process/task_queues:96:5)
> > at async file:///D:/Mechi-Server-2.0/server.js:114:9
> 
> Do you have access on the Bard website? Could you also make sure your PSID is correct?

Yes cookie working on googlebard module

**Comment by EvanZhouDev** [comment]
GoogleBard uses it prefixed with "__SecurePSID" or something like that. `bard-ai` just uses your cookie. Nothing prefixed.

**Comment by mashwishi** [comment]
> GoogleBard uses it prefixed with "__SecurePSID" or something like that. `bard-ai` just uses your cookie. Nothing prefixed.

So I tried removing ` __Secure-1PSID=` andstill has the same error `Error: Could not get Google Bard.`

**Comment by mashwishi** [comment]
So i have fixed the issue, i used the  ` __Secure-1PSID=` cookie instead of the ` __Secure-3PSID=`.

Now for the new Error:
```log
TypeError: Bard.ask is not a function
    at file:///D:/Mechi-Server-2.0/server.js:116:35
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by RFS-ADRENO** [comment]
> So i have fixed the issue, i used the ` __Secure-1PSID=` cookie instead of the ` __Secure-3PSID=`.
> 
> Now for the new Error:
> 
> ```
> TypeError: Bard.ask is not a function
>     at file:///D:/Mechi-Server-2.0/server.js:116:35
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
> ```

change to Bard.askAI

**Comment by mashwishi** [comment]
> askAI

Finally, again i would suggest making the `__Secure-1PSID=` dynamic or don't include this here and let user add the  `__Secure-XPSID=`
![image](https://github.com/EvanZhouDev/bard-ai/assets/62344860/17f5508f-a3ed-4306-8dd1-a30afb5164d9)



Working output:
![image](https://github.com/EvanZhouDev/bard-ai/assets/62344860/9308e2a3-ab2a-492b-b0fc-f6461b1d2a2b)

**Comment by EvanZhouDev** [comment]
Glad that it worked out in the end! As for the varied PSID, it will be put into consideration. Closing.
