### ISSUE TITLE
CORS error

### ISSUE THREAD

**Issue by muflahnasir123** [EvanZhouDev/bard-ai#2]
Hi There!

I am using `bard-ai` in React project so that I can generate content for my website. But I am getting a CORS error along with other issues upon running the website. I am running my website on the Chrome browser.

<img width="1440" alt="Screenshot 2023-05-27 at 12 53 11 PM" src="https://github.com/EvanZhouDev/bard-ai/assets/114991137/c85d98ae-d07f-4caa-8eba-97d3e72bd97c">

**Comment by muflahnasir123** [comment]
My `react` and `bard-ai` versions are:

`react`: `^18.0.0`
`bard-ai`: `1.1.3`

**Comment by EvanZhouDev** [comment]
I will test it myself later, but try again with the newest version of `bard-ai`. I have used the native `fetch()` function, so I don't know if it will help. If it doesn't I'll look at it further.

It is possible the only way to solve this is to use a proxy, however. If it is, I may implement it in a future update.

**Comment by Aldhanekaa** [comment]
> Hi There!
> 
> I am using `bard-ai` in React project so that I can generate content for my website. But I am getting a CORS error along with other issues upon running the website. I am running my website on the Chrome browser.
> 
> <img alt="Screenshot 2023-05-27 at 12 53 11 PM" width="1440" src="https://user-images.githubusercontent.com/114991137/241368465-c85d98ae-d07f-4caa-8eba-97d3e72bd97c.png">

I think you could try to use [Nextjs API Routes](https://nextjs.org/docs/pages/building-your-application/routing/api-routes), because it runs on server, this error probably because Google Bard API only accept request from server not client side.

**Comment by EvanZhouDev** [comment]
Yes... though OP is not necessarily using Next?

**Comment by EvanZhouDev** [comment]
Any updates @muflahnasir123? Closing otherwise...

**Comment by EvanZhouDev** [comment]
Custom callbacks will be available in Version 2. See #30.

Closing... feel free to re-open if necessary.
