### ISSUE TITLE
Having issues with getting images

### ISSUE THREAD

**Issue by 0zul** [EvanZhouDev/bard-ai#21]
![image](https://github.com/EvanZhouDev/bard-ai/assets/26915998/93cf54fb-dd55-426b-99d1-8b5c9dc4638d)

As per the screenshot, I'm unable to get response with images but others work perfectly fine.

**Comment by nainglynndw** [comment]
``url: x[0][5].match(/imgurl=([^&%]+)/)[1], `
remove that line from index.js and it will work
