### ISSUE TITLE
image link problem

### ISSUE THREAD

**Issue by jonvicbarcenas** [EvanZhouDev/bard-ai#22]
cannot send images

**Comment by ThatXliner** [comment]
Have you tried the latest version of the library?

**Comment by jonvicbarcenas** [comment]
Yes, no response from bard api if it contains images

**Comment by ThatXliner** [comment]
Please give us any error message, code you used, etc. to allow us to reproduce the problem.

**Comment by 0zul** [comment]
@ThatXliner I too am using the latest version still it doesn't work. #21

**Comment by jonvicbarcenas** [comment]
There is no error message, its just undefined, i copypaste your sample usage.

**Comment by EvanZhouDev** [comment]
Please show me your input and your output.

If you do not ask for an image, `images` will be `undefined`.

**Comment by jonvicbarcenas** [comment]
if text only it succeeds
![image](https://github.com/EvanZhouDev/bard-ai/assets/48144626/b4f51a2a-baec-4a68-9da5-02731b6595eb)


when image like cat image
![image](https://github.com/EvanZhouDev/bard-ai/assets/48144626/652c935f-a7ac-4767-8355-7ffa4cb34214)

**Comment by nainglynndw** [comment]
https://github.com/EvanZhouDev/bard-ai/issues/21#issuecomment-1627157519

**Comment by EvanZhouDev** [comment]
It should be fixed again in v1.5.1 Try updating and see if it works.

**Comment by jonvicbarcenas** [comment]
It workss!! Thankk youu

**Comment by EvanZhouDev** [comment]
Nice!

**Comment by jonvicbarcenas** [comment]
One last problem is, its not conversational anymore

**Comment by EvanZhouDev** [comment]
Are you using `Bard.Chat`? See documentation for more information. `askAI` is not supposed to be conversational.
