### ISSUE TITLE
text-to-action support 

### ISSUE THREAD

**Issue by ansarizafar** [EvanZhouDev/bard-ai#28]
It would be great If bardai has a built-in support for text-to-action like https://github.com/alexgriffithsdev/actionit

**Comment by ThatXliner** [comment]
I don’t think builtin support is a good idea. It would add unnecessary bloat to the library as the user could implement it themselves.

**Comment by EvanZhouDev** [comment]
What @ThatXliner said. Closing.

It may be possible for us to make something like this in the future, in another library.

**Comment by ansarizafar** [comment]
Microsoft has just released TypeChat https://microsoft.github.io/TypeChat/docs/introduction/ so we don't have to create our own library we just need to implement createLanguageModel function https://github.com/microsoft/TypeChat/blob/main/src/model.ts to use TypeChat with BardAI.
