### ISSUE TITLE
Could not get Google Bard.

### ISSUE THREAD

**Issue by atahanozer** [EvanZhouDev/bard-ai#29]
Hi, it was working fine for some time but today, I keep getting `Could not get Google Bard.` errors and can not make calls.

Checked the cookie and it is valid. Any ideas ?

**Comment by EvanZhouDev** [comment]
Go to bard.google.com, Clear Cookies, reload and sign in.
Then, get the new Cookie for __Secure-PSID1.

**Comment by atahanozer** [comment]
I did that and even logged in with a different account and updated __Secure-1PSID but still the same.

**Comment by Sidharth004** [comment]
Is there a way to overcome this issue?
Even if you sign in again and paste the new key, there are instances that it works well for some time but again gives the same error

**Comment by eerikson** [comment]
Evan's solution worked for about ten minutes before I experienced this error again. I doubt it's this library's fault, but some guidance on how often to expect this or how to work around it would be appreciated.
