### ISSUE TITLE
`bard-ai` v2.0

### ISSUE THREAD

**Issue by EvanZhouDev** [EvanZhouDev/bard-ai#30]
This is the feature tracker for `bard-ai` Version 2 (See `v2` branch). Here's what's in store:
- [x] 🏗️ API redesign
- [x] 🍪 Multiple Cookie Usage with `new Bard(COOKIE)`
- [x] ⚙️ Advanced Configuration with `{...config}` on `Bard` and `ask()`
- [x] 🔊 Verbose Mode
- [x] 🖼️ Photo input

What still needs to be done:
- [x] 💬 Re-implement Chat
- [x] 🍪 Different User Cookies: `__Secure-PSID${x}`
- [x] 🧪 Tests (with `vitest`)
    - [x] 📖 Extract a `Bard.parse` function that ensures text response is parsed correctly
    - [x] 🗓️ Daily Bard runs to ensure `bard-ai` is working fine
- [x] 📝 Separate README for GitHub and NPM (so that assets don't have to be downloaded)
- [x] 🏁 Finishing Touches
- [x] **Make sure to modify branch on test**

After everything has been re-imagined, we will be testing for a while, and it should be released!

**Comment by ThatXliner** [comment]
Remove "Auto `.env` Detection"

**Comment by EvanZhouDev** [comment]
Released!
