### ISSUE TITLE
Error when initializing Bard

### ISSUE THREAD

**Issue by OsmonKida** [EvanZhouDev/bard-ai#33]
Hey, I am getting a ReferenceError: fetch is not defined, 
when trying to initialize Bard with Bard.init("KEY"), I am calling the init function on a express js app route, am I doing a mistake?

**Comment by EvanZhouDev** [comment]
Yeah, `fetch` is an experimental feature in Node.js. With that said, please see https://bard-ai-docs.vercel.app/fetch

**Comment by OsmonKida** [comment]
Thank you, closing this issue then!

**Comment by ThatXliner** [comment]
@EvanZhouDev Another FAQ addition. Maybe you should start making a README issue template? You may modify mine (at ThatXliner/pyt2)
