### ISSUE TITLE
Error [ERR_REQUIRE_ESM]: require() of ES Module...

### ISSUE THREAD

**Issue by barrynorman** [EvanZhouDev/bard-ai#35]
Hello!

I'm trying to implement a short typescript script to play around, but somehow I am not able to get it running.
Here are the most important files. 

```
{
  "name": "bard",
  "version": "1.0.0",
  "description": "",
  "main": "./src/index.ts",
  "scripts": {
      "start": "ts-node ./src/index.ts"
  },
  "keywords": [],
  "author": "anon",
  "license": "ISC",
  "dependencies": {
    "@types/node": "^20.4.2",
    "bard-ai": "^1.5.4",
    "ts-node": "^10.9.1"
  }
}
```

```
import { askAI, init } from "bard-ai";

const COOKIE_KEY =
  "__Secure-1PSID=XXX";

const main = async () => {
  await init(COOKIE_KEY);
  console.log(await askAI("Hello world!"));
};

main();

```

When I try 

`npm run start`

i get this:
```
Error [ERR_REQUIRE_ESM]: require() of ES Module ~/bard/node_modules/bard-ai/index.js from ~/bard/src/index.ts not supported.
Instead change the require of index.js in ~/bard/src/index.ts to a dynamic import() which is available in all CommonJS modules.
```

Any idea why? I'm not sure if i understand the error.

**Comment by ThatXliner** [comment]
This isn't a bug of Bard, just a general JavaScript error. Try changing your `start` script to `ts-node --esm ./src/index.ts`

**Comment by EvanZhouDev** [comment]
Yep! `bard-ai` only works with modern "ESM" `import` syntax, as per standards these days.

**Comment by barrynorman** [comment]
Still not working. `--esm` does not help.
Did one of you tried my example?

**Comment by gelevanog** [comment]
try this

`async getBardText(text) {
    const importDynamic = new Function(
      'modulePath',
      'return import(modulePath)',
    );
    const { init, askAI } = await importDynamic('bard-ai');

    init(
      COOKIE_KEY
    );
    const res = await askAI('Hello bard!');
    return res;
  }`

**Comment by tuandev1l** [comment]
@gelevanog well, i tried this but it throws Error like this. I comment `await init(COOKIE_KEY);`, it throws error at askAI similar to init.
![image](https://github.com/EvanZhouDev/bard-ai/assets/86116547/aa446c4f-3c94-44b9-bb83-2ce19dce1fab)
