### ISSUE TITLE
Is it possible to use this module with CommonJS & ES5?

### ISSUE THREAD

**Issue by erturkdotgg** [EvanZhouDev/bard-ai#40]
### Prerequisites

- [X] I am using the latest version of bard-ai
- [X] I have searched the [issues](https://github.com/EvanZhouDev/bard-ai/issues) and believe that it has not already been requested (and possibly rejected)
- [X] I agree to follow the [Code of Conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct/)

### Feature description

Is it possible to use this module with CommonJS & ES5?

**Comment by ThatXliner** [comment]
This is not a feature request but instead a question. 

@EvanZhouDev perhaps we can set up GitHub discussions for questions. Or our own SO tag

**Comment by ThatXliner** [comment]
To answer your question
> ### Prerequisites
> * [x]  I am using the latest version of bard-ai
> * [x]  I have searched the [issues](https://github.com/EvanZhouDev/bard-ai/issues) and believe that it has not already been requested (and possibly rejected)
> * [x]  I agree to follow the [Code of Conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct/)
> 
> ### Feature description
> Is it possible to use this module with CommonJS & ES5?

This is a generic JavaScript question. Try searching up “javascript use es6 modules in commonjs”

**Comment by EvanZhouDev** [comment]
Yes, Dynamic Imports.
