### ISSUE TITLE
[Bug]: cors issue

### ISSUE THREAD

**Issue by rafalinliyosar** [EvanZhouDev/bard-ai#44]
### Prerequisites

- [X] I have searched the [issues](https://github.com/EvanZhouDev/bard-ai/issues) and believe that it has not already been reported
- [X] I have made sure this bug reproduces on the latest version
- [X] I agree to follow the [Code of Conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct/)

### Bug description

facing cors issue, while i run basic code

### Reproduction steps

1. cess to fetch at 'https://bard.google.com/' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

### Reproduces how often

I can reproduce this bug 100% of the time

**Comment by EvanZhouDev** [comment]
This is most likely because of the fact that you need a special `fetch` function in your environment. Easy fetch polyfilling will be available in `bard-ai` v2, but you can just find a browser fetch polyfill for whatever framework (or not) you're using, and assign if to "fetch." Stay tuned to #30!

**Comment by EvanZhouDev** [comment]
Closing for now, feel free to reopen if you need.

**Comment by ramyA2Z** [comment]
I am still facing this issue an am unable to proceed on anything !

**Comment by EvanZhouDev** [comment]
Hello! `bard-ai` v2 is now available. Try now...

**Comment by EvanZhouDev** [comment]
Otherwise, try using the new `palm-api` module.
