### ISSUE TITLE
✨ [FEATURE]: Ask questions with image input

### ISSUE THREAD

**Issue by ronalddas** [EvanZhouDev/bard-ai#45]
### Prerequisites

- [X] I have searched the [issues](https://github.com/EvanZhouDev/bard-ai/issues) and believe that it has not already been requested (and possibly rejected)
- [X] I am using the latest version of `bard-ai`

### Feature description

Hi, great library, would really like it to have the image input feature too, am talking about this https://github.com/dsdanielpark/Bard-API#bard-ask_about_image-method

**Comment by EvanZhouDev** [comment]
Image input is in V2. See issue #30 for release progress.
