### ISSUE TITLE
🐛 [BUG]: The API is identified as a robot after some requests

### ISSUE THREAD

**Issue by MarwanRadwan7** [EvanZhouDev/bard-ai#49]
### Prerequisites

- [X] I have searched the [issues](https://github.com/EvanZhouDev/bard-ai/issues) and believe that it has not already been reported
- [X] It occurs on the latest version of `bard-ai`
- [X] I have read the [FAQ](https://bard-ai.js.org/faq/) and there are no solutions there

### Bug Description

I am making an application based in bard AI and after some requests it gave me this error : 
`Error creating channel: Error: Could not get Google Bard.`
from the init function as the website identifies the api as a robot and when I try to open the website from the browser it gives me a captcha. 

### Reproduction Steps

```
const cookies = process.env.BARD_COOKIE;
await Bard.init(cookies);
const conversation = new Bard.Chat();
const response = await conversation.ask(question);
const userData = await conversation.export();
```

### Occurance Rate

I can reproduce this bug 50% of the time.

**Comment by EvanZhouDev** [comment]
To be honest, not much I can do about that. Try with the new __Secure-#PSIDTS cookie in `bard-ai` v2

**Comment by MarwanRadwan7** [comment]
> To be honest, not much I can do about that. Try with the new __Secure-#PSIDTS cookie in `bard-ai` v2
Ok, I will give it a try. And also, thank you for the nice documentation.

**Comment by EvanZhouDev** [comment]
Hope it works! 😅

**Comment by EvanZhouDev** [comment]
Any updates? Closing otherwise...
