### ISSUE TITLE
🐛 [BUG]: Error: Could not use your Cookie. Make sure that you copied correctly the Cookie with name __Secure-1PSID exactly. If you are sure your cookie is correct, you may also have reached your rate limit.

### ISSUE THREAD

**Issue by alokid** [EvanZhouDev/bard-ai#50]
### Prerequisites

- [X] I have searched the [issues](https://github.com/EvanZhouDev/bard-ai/issues) and believe that it has not already been reported
- [X] It occurs on the latest version of `bard-ai`
- [X] I have read the [FAQ](https://bard-ai.js.org/faq/) and there are no solutions there

### Bug Description

![image](https://github.com/EvanZhouDev/bard-ai/assets/138843462/2571b55b-5a13-4138-b67f-94748be333bf)
even though I use the same key, but using the bard-ai module gets this error, but if using the googlebard module, it works.

### Reproduction Steps

let bot = new Bard(bardKey);

console.log(await bot.ask("Hello world!"));
console.log(await bot.ask("What is 1+1?"));
console.log(await bot.ask("What about 2+2?"));
console.log(await bot.ask("Goodbye."));

### Occurance Rate

I can reproduce this bug 100% of the time.

**Comment by EvanZhouDev** [comment]
I assume your key starts something like “__Secure-1PSID=”

If this is so, you can remove this for `bard-ai`.

If it starts with a non-1 PSID, put it as a JSON in the same place you put a cookie, like this:
```javascript
{
    “__Secure-2PSID”: “YOUR_COOKIE”
}
```

**Comment by alokid** [comment]
even though yesterday's version of the bard-ai module was working, the latest update, made it encounter an error

**Comment by EvanZhouDev** [comment]
Again, what format is the string you are putting into the object?

**Comment by alokid** [comment]
import Bard from "bard-ai";

let myBard = new Bard(<cookie>);

console.log(await myBard.ask("Hello, world!"));

**Comment by EvanZhouDev** [comment]
What are you putting into `new Bard()`? Does it start with “__Secure-PSID”?

**Comment by alokid** [comment]
without text "__Secure-1PSID", but I only entered cookies

**Comment by EvanZhouDev** [comment]
Hmm… very strange. I will have to look into it tomorrow. Have you tried using the PSIDTS? (In the FAQ)

**Comment by alokid** [comment]
I have tried many times, changing google accounts. the results are not satisfactory.

**Comment by xLSX285** [comment]
Same here, my __Secure-1PSID doesn't seem to work with 2.0.0, when I go back to 1.5.4 it works just fine on my end.

**Comment by EvanZhouDev** [comment]
So sorry, should be all fixed now...

**Comment by EvanZhouDev** [comment]
By the way @xLSX285 your PSIDTS should be used _alongside_ your PSID... not alone, like this:
```
let bot = new Bard({
    "__Secure-1PSID": PSID,
    "__Secure-1PSIDTS": PSIDTS
})
```

Hope this helps!

**Comment by alokid** [comment]
![image](https://github.com/EvanZhouDev/bard-ai/assets/138843462/e2977cd0-536e-4daa-8495-9fcc1c59b1b4)
let bot = new Bard({
    "__Secure-1PSID": bardKey,
    "__Secure-1PSIDTS": bardKey2
})

console.log(await bot.ask(m.text));
m.reply(await bot.ask(m.text))

**Comment by ThatXliner** [comment]
> ![image](https://user-images.githubusercontent.com/138843462/258617171-e2977cd0-536e-4daa-8495-9fcc1c59b1b4.png) let bot = new Bard({ "__Secure-1PSID": bardKey, "__Secure-1PSIDTS": bardKey2 })
> 
> console.log(await bot.ask(m.text)); m.reply(await bot.ask(m.text))
> 
> Latest Version

Are you sure you're updated to v2? and how are you importing bard?

**Comment by xLSX285** [comment]
> By the way @xLSX285 your PSIDTS should be used _alongside_ your PSID... not alone, like this:
> 
> ```
> let bot = new Bard({
>     "__Secure-1PSID": PSID,
>     "__Secure-1PSIDTS": PSIDTS
> })
> ```
> 
> Hope this helps!

Oh right.. can confirm it works now for me on 2.0.1!

**Comment by alokid** [comment]
> > ![image](https://user-images.githubusercontent.com/138843462/258617171-e2977cd0-536e-4daa-8495-9fcc1c59b1b4.png) let bot = new Bard({ "__Secure-1PSID": bardKey, "__Secure-1PSIDTS": bardKey2 })
> > console.log(await bot.ask(m.text)); m.reply(await bot.ask(m.text))
> > Latest Version
> 
> Are you sure you're updated to v2? and how are you importing bard?

import Bard from "bard-ai";

let myBard = new Bard(COOKIE __Secure-1PSID);

console.log(await myBard.ask("Hello, world!"));

**Comment by anirudhv** [comment]
Try logging out, logging in again, and getting a new cookie. That works.

**Comment by preveenraj** [comment]
```let bot = new Bard({
    "__Secure-1PSID": PSID,
    "__Secure-1PSIDTS": PSIDTS
})```

Why do we have to use `__Secure-1PSIDTS` in the latest version?

**Comment by EvanZhouDev** [comment]
Seems like this is all fixed, to some degree. Closing for now.
