### ISSUE TITLE
Error: TypeError: Cannot read properties of nul l (reading '4')

### ISSUE THREAD

**Issue by siam38** [EvanZhouDev/bard-ai#53]
### Prerequisites

- [X] I have searched the [issues](https://github.com/EvanZhouDev/bard-ai/issues) and believe that it has not already been reported
- [X] It occurs on the latest version of `bard-ai`
- [X] I have read the [FAQ](https://bard-ai.js.org/faq/) and there are no solutions there

### Bug Description

const answer = chatData[4][0];

TypeError: Cannot read properties of nul l (reading '4') at #query (file:///home/runner/node- api/node_modules/bard-ai/index.js:240:32)

at process.processTicksAndRejections (node: internal/process/task_queues:95:5 )

at async Bard.ask (file:///home/runn er/node-api/node_modules/bard-ai/index.j s:342:24)

at async file:///home/runner/node-api/test.js:7:13

### Reproduction Steps

See err

### Occurance Rate

I can reproduce this bug 100% of the time.

**Comment by HalcyonAlcedo** [comment]
I have encountered the same problem, and after investigation, I found that the reason is that my server is not in the available area of Bard. When I switch to a US server, this problem no longer occurs

**Comment by ThatXliner** [comment]
Is this issue still existent with the latest version of bard-ai? If no, please close the issue

**Comment by Triggered0** [comment]
`0|bot      | TypeError: Cannot read properties of null (reading '4')
0|bot      |     at #query (file:///C:/Users/Administrator/Desktop/ForeverV14/node_modules/bard-ai/index.js:240:32)
0|bot      |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
0|bot      |     at async Chat.ask (file:///C:/Users/Administrator/Desktop/ForeverV14/node_modules/bard-ai/index.js:353:32)
0|bot      |     at async Object.execute (C:\Users\Administrator\Desktop\ForeverV14\src\events\messageCreate.js:224:31)`

bard-ai@2.0.3
node v18.13.0
