### ISSUE TITLE
fix-esm issue to use bard-ai.

### ISSUE THREAD

**Issue by erturkdotgg** [EvanZhouDev/bard-ai#55]
### Prerequisites

- [X] I have searched the [issues](https://github.com/EvanZhouDev/bard-ai/issues) and believe that it has not already been reported
- [X] It occurs on the latest version of `bard-ai`
- [X] I have read the [FAQ](https://bard-ai.js.org/faq/) and there are no solutions there

### Bug Description

I was using bard-ai with this instead of import:
const Bard = require("fix-esm").require("bard-ai");

It was working great. But after the bard-ai v2:

It started to give this error:
_**TypeError: Bard is not a constructor**_

Is it still possible for me to use it? I was be able to use it before the v2. 
Currently impossible for me to use import.

### Reproduction Steps

Use fix-esm.

### Occurance Rate

I can reproduce this bug 100% of the time.

**Comment by Aldhanekaa** [comment]
Try to use this instead

```javascript

(async function () {
  const Bard = await import('bard-ai');


```

that works for me for my javascript project that use `require`.

**Comment by Triggered0** [comment]
```js
(async function () {
    const Bard = (await import('bard-ai')).default;
})();
```

**Comment by alisson-js** [comment]
you need to use like this

`const Bard = require('fix-esm').require('bard-ai').default;`

that works
