### ISSUE TITLE
Why does it not respond sonetimes?


### ISSUE THREAD

**Issue by jonvicbarcenas** [EvanZhouDev/bard-ai#9]

**Comment by EvanZhouDev** [comment]
Please give steps to reproduce. Unfortunately, I am not able to help you with someone that I cannot see happening myself, with no description of the issue whatsoever. However, try checking your network connection and making sure it is stable. Will be closing if no further information is provided.

**Comment by jonvicbarcenas** [comment]
It's working now, thank you! I just checked your package on npm, it was under construction, so that might have been why it wasn't responding.

**Comment by EvanZhouDev** [comment]
Great to hear!
